# Generated by Django 3.2.18 on 2023-04-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('black_spot', 'Black Spot'), ('brown_blight', 'Brown Blight'), ('tip_burn', 'Tip Burn')], max_length=20)),
                ('cure_description', models.TextField()),
            ],
        ),
    ]
