# Generated by Django 3.2.18 on 2023-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cure',
            name='plant',
            field=models.CharField(choices=[('cinnamon', 'Cinnamon'), ('coconut', 'Coconut')], default='coconut', max_length=20),
        ),
    ]
