# Generated by Django 3.2.18 on 2023-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cure_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='disease',
            field=models.CharField(choices=[('black_spot', 'Black Spot'), ('brown_blight', 'Brown Blight'), ('tip_burn', 'Tip Burn'), ('RoughBark', 'Rough Bark'), ('StripeCanker', 'Strip Cancer')], max_length=20),
        ),
    ]
